"""add user type

Revision ID: 340fe35912a7
Revises: 0a8c8d03e0a4
Create Date: 2026-08-14 16:45:02.911979

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340fe35912a7'
down_revision: Union[str, Sequence[str], None] = '0a8c8d03e0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_type_enum = postgresql.ENUM(
        "owner",
        "admin",
        "member",
        name="usertype",
    )
    user_type_enum.create(op.get_bind())
    op.add_column('users', sa.Column(
            "user_type",
            user_type_enum,
            nullable=False,
            server_default="owner",
            ))
    op.alter_column(
        "users",
        "user_type",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("users", "user_type")

    user_type_enum = postgresql.ENUM(
        "owner",
        "admin",
        "member",
        name="usertype",
    )

    user_type_enum.drop(op.get_bind())
