"""add deleted_at to tickets

Revision ID: 8582e37f3cec
Revises: 465fd985b4c5
Create Date: 2026-08-21 19:02:50.098203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8582e37f3cec'
down_revision: Union[str, Sequence[str], None] = '465fd985b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'deleted_at')
    # ### end Alembic commands ###
